dist: xenial
sudo: false

language: go
go_import_path: github.com/opensds/nbp

go:
  - 1.11.x
  - tip

env:
  matrix:
   - TARGET=amd64

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

install:
  - make

script:
  - go test -v github.com/opensds/nbp/csi/... -cover
  - go test -v github.com/opensds/nbp/flexvolume/... -cover
  - go test -v github.com/opensds/nbp/cindercompatibleapi/... -cover

after_success:
  # Clean OpenSDS northbound plugin built data
  - make clean
