# This YAML file contains nginx & csi opensds driver objects,
# which are necessary to run nginx with csi opensds driver.

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: csi-data-opensdsplugin 
  volumes:
  - name: csi-data-opensdsplugin
    persistentVolumeClaim:
      claimName: opensdspvc
      readOnly: false
